---
- name : 同步文件 sync files
  synchronize :
    src  : /software
    dest : /
    delete : yes
    #rsync_timeout : 10
  register : reload

- name : 创建链接目录 create soft link
  file :
    state : directory
    path : /etc/nginx/{{ item.dir }}
  with_items :
    - { dir : 'conf' }
    - { dir : 'kis' }

- name : 域名证书及配置文件软链接 ssl and configurations soft link
  file :
    state : link
    src : /software/{{ item.name }}
    path : /etc/nginx/{{ item.dir }}/{{ item.name }}
  register : result
  with_items :
    - { dir : 'conf', name : '域名证书' }
    - { dir : 'kis', name : '站点配置文件' }

- name : 检测Web应用 Detact web server apps
  stat :
    path : /usr/bin/openresty
  register: p

- name : 修改文件夹属主 chown
  shell : chown nginx. /etc/nginx/{{ item.dir }} -R
  args :
    warn: False
  when : result is changed and p.stat.exists == False
  with_items :
    - { dir : 'conf' }
    - { dir : 'kis' }

- name : 重载nginx配置 Reload Nginx
  service :
    name : nginx
    state : reloaded
  when : reload is changed and p.stat.exists == False

- name : 重载Openresty配置
  service :
    name : openresty
    state : reloaded
  when : p.stat.exists == True
  register : check_openresty
